Bilge yaklaşık bir ay öncesine kadar evsizdi ve yollarda yaşıyordu. Tam olarak parasız değildi, günde üç öğün besinini alıyor, geri kalan zamanında şehrin sokaklarında dolaşıyor, çevreyi ve insanları izleyip kafasına gelen düşüncelerin yararlı olup olmadıklarına karar veriyordu. Her düşünceye artı bir veya eksi bir puan verme tekniği ile ilgili bir şey okumuştu, eksi bir veriyorsa o düşünceyi gömmeye ve yeni düşüncelere açılmaya çabalıyordu. Nadiren eksi bir verdiği düşüncelerle baş başa kalırdı. Her düşünceden bir şeyler çıkarmaya, onu parçalara ayırıp içinde değerli ne varsa almaya çalışıyordu.

Gözlemlerinden biri şuydu: İnsanlar birbirlerine öneri vermeyi seviyorlardı. Hoşlandıkları veya yararlı olabileceğini düşündükleri şeyleri çevreleriyle paylaşmak istiyorlardı. Özellikle yakın çevreleriyle, çünkü bu daha kolaydı ve fazla enerjiye mal olmuyordu. Harcadıkları görece az enerjiye karşılık çevrelerinden kendilerini mutlu edecek, bu enerjinin karşılığını fazlasıyla verecek tepkiler alıyorlardı. Genel olarak tüm insanları etkilemek, onlara öneri vermek de kesinlikle insanların ilgisini çekiyordu ama bu daha fazla enerji demekti. Günümüzde kitlelere ulaşmak çok daha kolaydı, herkesin içinde bulunduğu muazzam bir ağ, inanması güç bir iletişim aracı vardı, internet. Yine de insanlara ulaşmak enerji ve belli alanlarda geliştirilmiş yeteneklere ihtiyaç duyuyordu.

Bu gözlemin üzerine düşünürken Bilge'nin zihninden geçen düşüncelerden biri de şuydu: İnsanlar, saygı duydukları, kendilerinden daha başarılı ve ilgilendikleri alanlarda üst düzey buldukları insanlara öneri vermeyi -özellikle de onlar öneriye ihtiyaçları olduğunu belirttiklerinde- gerçekten çok seviyorlardı. Bu onları tatmin ediyordu, kendilerini işe yarar ve her zaman söylendiği gibi "kendilerinin daha iyi bir versiyonu" haline geldiklerini düşündürüyor, ya da bir şekilde hissettiriyor olmalıydı.

Bilge yeni bir sektör keşfetmiş olabileceğini fark etti. Düşüncesini lisede çeşitli çılgınlıklar yaptıkları dostu X ile paylaştı. Bu çılgınlıklar genelde çılgınlık deyince insanların hayal ettiği çılgınlıklardan değildi, bu çılgınlıklar kelimelerle oynamak, düşünceleri birbiri içine geçirerek zincir haline getirip zinciri başka bir zincire bağlayarak zincirlerden oluşan bir yumağı okul camından aşağı sarkıtıp müdüre "tamam hocam, giriyoruz içeri" diye bağırmak gibi çılgınlıklardı. Daha soyut, kafalarının içinde çılgınlıklar. Birçoğunu yalnızca bu iki dost anlayabiliyordu. Kendi değerlerini, kültürlerini oluşturmuşlardı. Zincir yumağını bir daha camdan içeri çekemediler.

X, Bilge'nin fikrini beğenmişti. Fikir, insanların Bilge'ye para ödeyerek ona gelip önerilerde bulunmaları üstüne kuruluydu. Öneri başına para alacaktı. Fakat öneriyi almakla kalmayacak, içeri çekemedikleri o zincir yumağına ulaşmak için camdan dışarı çıkacaktı. Her konuğu ile verdikleri öneri üzerinde bir yolculuğa çıkacak, önerinin boşluklarından içeri girecek, boşlukları patates ile doldurup tekrar çıkarken her adımda öneriyi daha kullanılabilir, pratik hale getireceklerdi.

Bilge düşünmeyi seviyordu. Düşünecek yeni bir şeyler aradığı zamanlar oluyordu ki bu zamanlar genelde beyninin düşünmeye bir süre ara vererek dinlenmek istediği zamanlardı. Yeni bir şeyler aradığında düşünmemesi gerektiğini anlıyordu. Bu zamanlar onu rahatlatıyordu. Fakat şunu da fark etmişti, bu zamanlar dışında düşündüğü her şey bir anlam ifade ediyordu ve düşünmek için sonsuz kaynak vardı. Kaynak olarak ne beslerse kendinden oluşan sisteme, sistem kendi içinde bazı çıkışlar veriyor, bu çıkışlardan bazılarını tekrar girişler halinde sisteme kazandırırken bazılarını da ayağa kalkıp pantolonunu kaldırdıktan sonra sifonu çekerek şehir kanalizasyon sistemine gönderiyordu. Tuvaletlerin düşünmek için ideal ortamlardan olduğunu o da kabul ediyordu. Ama banyo yapmayı tercih ederdi. İnsan düşünsel sürecinin doruk noktası olan banyo vakitlerini çok seviyordu. Düşüncelerin suyla birlikte zihninde akması, kimisinin süzülerek farklı noktalara ulaşması hoşuna gidiyordu. Bunun için özel bir çaba harcaması gerekmiyordu, düşünüyordu ki banyolar bu verimin sağlanması üzerine yapılmış karmaşık ve anlaması güç bilimsel çalışmaların sonuçlarından faydalanılarak ve her detayı düşünülerek tasarlanıyorlardı. Kesinlikle yanılıyordu, yanıldığını ise biliyordu. Bu da banyoda aklından geçen düşüncelerden biriydi yalnızca.

Arkadaşı X ona borç para vermeyi teklif etti, böylece Bilge bir ofis tutacak ve gerekli donanımla birlikte kendi bireysel Öneri Alma Şirketi'ni kurabilecekti. Bir internet sitesi açacaklar ve ödemeyi kesinlikle internet üzerinden alacaklardı. Ofiste para sesi veya kokusu veya görüntüsü istemediklerinden eminlerdi.

Bilge çok yüksek olmayan bir iş merkezinden bir ofis kiraladı. Bu işi en azından bir yıl boyunca sürdürmek isteğindeydi. Ofis tek odaydı, duvarları siyaha boyattı. Yerler bordo zemin rengi üstüne siyah noktalı bir halı ile kaplandı. Bir sıra makinesi bulundu ve kırmızı LED'lerden oluşan uzaktan kumandalı bir sıra sayacı alındı. İşin en eğlenceli kısmı IKEA'ya gitmek ve bir ofiste olmasını isteyeceği şeyleri almaktı. Koyu kahverengi ahşap bir masa, bir masa lambası, bir metal kalem kutusu ve bir ... . Ayrıca, unutmadan, müthiş rahat, vücudunun her türlü oturma pozisyonuna uyum sağlayabilecek rahat bir patron koltuğu. Sade bir ofisti, Bilge'nin istediği gibi.


